### ISSUE TITLE
how to extend femanager in TYPO3 10

### ISSUE THREAD

**Issue by MoppieMop** [in2code-de/femanager#245]
I am not able to extend femanager anymore in TYPO3 10. I use femanager 6.0.0.

I did everything in https://stackoverflow.com/questions/47836944/extend-typo3-femanager.
I also replaced the deprecated stuff - something like /Configuration/Extbase/Persistence/Classes.php
```php
//I have no idea if this is right
\In2code\Femanager\Domain\Model\User::class => [
        'subclasses' => [
            0 => '\VENDOR\NAME\Domain\Model\User'
        ]
    ],
\VENDOR\NAME\Domain\Model\User::class => [
        'tableName' => \In2code\Femanager\Domain\Model\User::TABLE_NAME,
        'recordType' => 0,
        'properties' => [
            'new_field' => [
                'fieldName' => 'new_field'
            ],
        ]
    ],
...
```

and in  ext_localconf.php
```php
        \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
            ->registerImplementation(\In2code\Femanager\Controller\NewController::class, \VENDOR\NAME\Controller\NewUserController::class);
        \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
            ->registerImplementation(\In2code\Femanager\Controller\EditController::class, \VENDOR\NAME\Controller\EditUserController::class);
...
```

But on user register I always get `Call to a member function attach() on null`. I think the user-Object is not instanciated correct. Can please someone provide an working example?

**Comment by typo3-solution** [comment]
I extended the femanger in TYPO3V10 successfully. Checkt this out: https://docs.typo3.org/p/in2code/femanager/6.0/en-us/Features/NewFields/Index.html It works very well! :-)

**Comment by sciloqi** [comment]
classes.php

`<?php

declare(strict_types=1);

return [
    \Buero7\HansewasserIntranet\Domain\Model\User::class => [
        'tableName' => 'fe_users',
        'recordType' => '0',
    ],
];
`

ext_localconf.php

`
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
    ->registerImplementation(\In2code\Femanager\Domain\Model\User::class, \Buero7\HansewasserIntranet\Domain\Model\User::class);
`

see: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by MoppieMop** [comment]
Did anyone use usergroups. I found out, the whole problem is with usergroups. Apparently {allUserGroups} does not work anymore. And even when when I bypass this step in registration ({1:'group1'}), I got following errors:
`Object of type TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup with identity "1" not found.` 
But I have an Usergroup-Object with uid=1.

**Comment by MoppieMop** [comment]
For now I have a hotfix - not a good one, but it is finally a running extend_fe_manager on TYPO3 v10.
I had to override the `addUsergroup` function in the User-Model:
```
    /**
     * Adds a usergroup to the frontend user
     *
     * @param \In2code\Femanager\Domain\Model\UserGroup $usergroup
     */
    public function addUsergroup(UserGroup $usergroup)
    {

        if (!$this->usergroup) {
            $this->usergroup = new ObjectStorage();
        }
        $this->usergroup->attach($usergroup);
    }
```

somehow the usergroup  is not initialized.
And as I said, `{allUserGroups}` is not working, so I had to replace it as well.

**Comment by andrekoller** [comment]
> classes.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> return [
>     \VENDOR\NAME\Domain\Model\User::class => [
>         'tableName' => 'fe_users'
>     ],
> ];
> ```
> 
> ext_localconf.php
> 
> ```
> \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
>     ->registerImplementation(\In2code\Femanager\Domain\Model\User::class, \VENDOR\NAME\Domain\Model\User::class);
> ```
> 
> see: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

I tried this solution but without success

The new properties are shown in debug but all properties are empty in  Frontend. In Backend everything works fine.
Can anyone help?

**Comment by jackermann** [comment]
@andrekoller Have you found a solution? I have the same problem.

**Comment by treac1e** [comment]
Same Problem here. 

It would be really great have an update of the section in the femanager manual "Adding new fields to fe_users with your own extension" (https://docs.typo3.org/p/in2code/femanager/6.1/en-us/Features/NewFields/Index.html) that works with TYPO3 10.

**Comment by Patta** [comment]
Same here.

**Comment by Patta** [comment]
PR #254 and #255 seems to fix this issue and extending like in the above issue text works. But now other things do not work properly. Redirect after creation is wrong. Exception after adminConfirmation "Call to a member function get() on null | Error thrown in file ...\ext\femanager\Classes\Finisher\FinisherRunner.php"...

**Comment by sbusemann** [comment]
This is resolved now with https://github.com/in2code-de/femanager/pull/322

**Comment by typoworx-de** [comment]
Well having to struggle with customer still having TYPO3 v10 (yes I know...blame, it really sucks for me). This PR does still not resolve the issue.

Why are you not simply using UserIngterface this would make things much more flexible instead of strugging with NewController overrides just to add one new property using Custom Model this is really a lot of overhead for such a simple task ..
