### ISSUE TITLE
Please approve some translations

### ISSUE THREAD

**Issue by oliverklee** [in2code-de/femanager#578]
There are some suggested German translations on Crowdin that need approval to be downloadable in TYPO3. Could you please check and approve them? Thanks!

https://crowdin.com/project/typo3-extension-femanager/de

**Comment by sbusemann** [comment]
done!

**Comment by oliverklee** [comment]
Thanks! :pray:

**Comment by oliverklee** [comment]
"diverse"/"divers" is still not approved: https://crowdin.com/editor/typo3-extension-femanager/5094/en-de?view=comfortable&filter=basic&value=0

**Comment by sbusemann** [comment]
seems there went something wrong  - it should work
